### ISSUE TITLE
Tracking bug for testing improvements

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#1845]
### CI improvements (reduce time it takes for Github actions to run):
- [ ] DWDS tests should be sharded into ~3 groups (currently they take much longer than the other CI actions)
- [ ] Consider moving tests with a large timeout limit (eg, the [`devtools _test`](https://github.com/dart-lang/webdev/blob/80f8671d5db1d4ee9577f8f407aa64f5697b1dea/dwds/test/devtools_test.dart#L5) at 5 minutes) to a cron job

### Refactor `TestContext` setup:
- [ ] Make `TestServer` more re-usable (described in https://github.com/dart-lang/webdev/issues/1779)
- [ ] Make it clearer what parameters should be passed to `TestContext` (eg, it is unclear the difference between `path` vs `pathToServe`). Also the default Dart entry file is in `append_body`, but the default HTML entry file is in `hello_world`.

### Other improvements:
- [ ] Callstack tests break if test `fixtures` are formatted (described in https://github.com/dart-lang/webdev/issues/1831)
- [ ] All packages should have a `mono_pkg.yml` file, so that the `analyze` and `format` steps can be run against them during CI 
- [ ] Support Dart 3.0 breaking changes in tests (tracked in https://github.com/dart-lang/webdev/issues/1818)
