### ISSUE TITLE
Tracking bug: Changes to the Dart VM service interface should be easier to roll out across `vm_service` and `dwds`

### ISSUE THREAD

**Issue by elliette** [dart-lang/webdev#2093]
Tracking bug for [go/dwds-vm-service-proposal](http://go/dwds-vm-service-proposal):

To address Issue #1 (It is easy for developers to accidentally make changes to package:vm_service that end up breaking web debugging workflows):

- [x] During development, package:dwds will depend on `package:vm_service` as a git dependency override (see: https://github.com/dart-lang/webdev/pull/2078). 
- [ ] Any breaking changes of the VM Service interface will be caught during development of `package:dwds` due to the dependency override. We should also add a daily cron job to further detect this.
- [x] When `package:dwds` is ready to be released, the dependency override will need to be removed (see: https://github.com/dart-lang/pub/pull/3782).

To address Issue #2 (Unblocking Dart SDK rolls into google3 after a change to the Dart VM Service interface is a painful process):

- [x] Roll `package:dwds` into google3 with the Dart SDK

**Comment by bkonyi** [comment]
Handled by introducing `package:vm_service_interface` and using the VM service packages as Git dependencies.
